### ISSUE TITLE
Carrierwave 3.x changed and added some translation keys

### ISSUE THREAD

**Issue by araccaine** [carrierwaveuploader/carrierwave-i18n#25]
Carrierwave had some updates to their translation keys since version 3, see [`lib/carrierwave/locale/en.yml`](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/locale/en.yml):

- `rmagick_processing_error` and `mini_magick_processing_error` were merged to `processing_error`
- `_width_` and `_heigth_` errors were added

```yaml
en:
  errors:
    messages:
      carrierwave_processing_error: failed to be processed
      carrierwave_integrity_error: is not of an allowed file type
      carrierwave_download_error: could not be downloaded
      extension_allowlist_error: "You are not allowed to upload %{extension} files, allowed types: %{allowed_types}"
      extension_denylist_error: "You are not allowed to upload %{extension} files, prohibited types: %{prohibited_types}"
      content_type_allowlist_error: "You are not allowed to upload %{content_type} files, allowed types: %{allowed_types}"
      content_type_denylist_error: "You are not allowed to upload %{content_type} files"
      processing_error: "Failed to manipulate, maybe it is not an image?"
      min_size_error: "File size should be greater than %{min_size}"
      max_size_error: "File size should be less than %{max_size}"
      min_width_error: "Image width should be greater than %{min_width}px"
      max_width_error: "Image width should be less than %{max_width}px"
      min_height_error: "Image height should be greater than %{min_height}px"
      max_height_error: "Image height should be less than %{max_height}px"
```

(This is also slightly related to #3. `carrierwave-i18n` currently does not indicate any version-dependency for `carrierwave`)
